name: vaishnav_parivar
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  bot_toast: ^4.0.0
  flutter_svg: ^1.0.0
  hexcolor: ^2.0.5
  country_code_picker: ^2.0.2
  assets_audio_player: ^3.0.4+1
  intl: ^0.17.0
  cached_network_image: ^3.2.0

  dropdown_button2: ^1.0.7
  percent_indicator: ^4.0.0
  photo_manager: ^1.3.10
  pinput: ^1.2.0
  better_player: ^0.0.70
  file_picker: ^3.0.1
  loading_indicator: ^3.0.3
  email_validator: ^2.0.1
  firebase_auth: ^3.3.10
  flutter_easyloading: ^3.0.3
  firebase_database: ^7.2.0
  firebase_core: ^1.12.0
  firebase_messaging: ^11.2.10
  expandable_text: ^2.2.0
  permission_handler: ^8.2.0
  firebase_storage: ^10.2.7
  # firebase_core: ^1.6.0
  # firebase_messaging: ^11.2.5
  flutter_local_notifications: ^5.0.0+4
  firebase_in_app_messaging: ^0.6.0+6  # use for firebase notifications
  firebase_analytics: ^9.0.5 # use firebase anlytics
  flutterfire_installations: ^0.1.0
  device_info_plus: ^3.2.2
  platform_device_id: ^1.0.1
  flutter_native_timezone: ^2.0.0
  get_storage: ^2.0.3
  cloud_firestore: ^3.1.10
  shimmer: ^2.0.0
  http: ^0.13.4
  firebase_remote_config: ^2.0.2 # use for force update


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/png/
    - assets/svg/
    - assets/video/
    - assets/audio/
  fonts:
    - family: sf_normal
      fonts:
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF